version: "2"
linters:
  disable:
    - unused
  settings:
    goconst:
      ignore-tests: true
    ireturn:
      allow:
        - error
        - stdlib
        - github.com/git-pkgs/spdx.Expression
