version: "2"
linters:
  disable:
    - unused
  exclusions:
    rules:
      - path: normalize.go
        linters:
          - goconst
  settings:
    goconst:
      ignore-tests: true
    ireturn:
      allow:
        - error
        - stdlib
        - github.com/git-pkgs/spdx.Expression
