package spdx

import "testing"

// TestSPDXCorrectCompatibility tests our implementation against spdx-correct.js test cases.
// spdx-correct.js is maintained by a license lawyer and is the de facto standard.
// Source: https://github.com/jslicense/spdx-correct.js/blob/main/test.js
func TestSPDXCorrectCompatibility(t *testing.T) {
	// These are the test cases from spdx-correct.js with upgrade: true (default)
	cases := map[string]string{
		// BSD variants
		"BSD":                    "BSD-2-Clause",
		"BSD 2-Clause":           "BSD-2-Clause",
		"BSD 2-Clause license":   "BSD-2-Clause",
		"BSD 2-clause":           "BSD-2-Clause",
		"BSD 3-Clause":           "BSD-3-Clause",
		"BSD 3-clause":           "BSD-3-Clause",
		"BSD 3":                  "BSD-3-Clause",
		"BSD 4-Clause":           "BSD-4-Clause",
		"BSD-2 Clause":           "BSD-2-Clause",
		"BSD-3 Clause":           "BSD-3-Clause",
		"BSD-3":                  "BSD-3-Clause",
		"BSD3":                   "BSD-3-Clause",
		"BSD-3-Claude":           "BSD-3-Clause",
		"2 clause BSD":           "BSD-2-Clause",
		"2-clause-BSD":           "BSD-2-Clause",
		"3-Clause BSD":           "BSD-3-Clause",
		"3-Clause-BSD":           "BSD-3-Clause",
		"3-clause BSD":           "BSD-3-Clause",
		"BSD clause 3":           "BSD-3-Clause",
		"BS3 3-Clause":           "BSD-3-Clause",
		"Modified BSD":           "BSD-3-Clause",
		"New BSD":                "BSD-3-Clause",
		"Old BSD":                "BSD-4-Clause",
		"Original BSD License":   "BSD-4-Clause",
		"Standard 3-clause BSD":  "BSD-3-Clause",
		"Simplified BSD Licese":  "BSD-2-Clause",
		"Clear BSD License":      "BSD-3-Clause-Clear",
		"Free BSD":               "BSD-2-Clause-FreeBSD",
		"FreeBSD":                "BSD-2-Clause-FreeBSD",
		"NetBSD":                 "BSD-2-Clause-NetBSD",

		// Apache variants
		"Apache":                          "Apache-2.0",
		"Apache ":                         "Apache-2.0",
		"APACHE":                          "Apache-2.0",
		"APACHE 2":                        "Apache-2.0",
		"APACHE 2.0":                      "Apache-2.0",
		"APACHE-2":                        "Apache-2.0",
		"APACHE-2.0":                      "Apache-2.0",
		"APACHE2":                         "Apache-2.0",
		"Apache 2":                        "Apache-2.0",
		"Apache 2.0":                      "Apache-2.0",
		"Apache-2":                        "Apache-2.0",
		"Apache-2.0":                      "Apache-2.0",
		"Apache2":                         "Apache-2.0",
		"Apache 2 License":                "Apache-2.0",
		"Apache 2.0 License":              "Apache-2.0",
		"Apache License":                  "Apache-2.0",
		"Apache License 2":                "Apache-2.0",
		"Apache License 2.":               "Apache-2.0",
		"Apache License 2.0":              "Apache-2.0",
		"Apache License, Version 2.0":     "Apache-2.0",
		"Apache License, version 2":       "Apache-2.0",
		"Apache License Version 2.0":      "Apache-2.0",
		"Apache Licence 2.0":              "Apache-2.0",
		"Apache Licence v2":               "Apache-2.0",
		"Apache License v2":               "Apache-2.0",
		"Apache License v2.0":             "Apache-2.0",
		"Apache License V2":               "Apache-2.0",
		"Apache License V2.0":             "Apache-2.0",
		"Apache Software License 2.0":     "Apache-2.0",
		"Apache Software License Version 2": "Apache-2.0",
		"Apache Public License v2":        "Apache-2.0",
		"Apache V2":                       "Apache-2.0",
		"Apache V2.0":                     "Apache-2.0",
		"Apache v2":                       "Apache-2.0",
		"Apache v2.0":                     "Apache-2.0",
		"Apache Version 2":                "Apache-2.0",
		"Apache Version 2.0":              "Apache-2.0",
		"Apache version 2":                "Apache-2.0",
		"Apache version 2.0":              "Apache-2.0",
		"Apache v. 2":                     "Apache-2.0",
		"Apache lisence V2":               "Apache-2.0",
		"Apache lisense 2.0":              "Apache-2.0",
		"APL":                             "Apache-2.0",
		"APL 2.0":                         "Apache-2.0",
		"APL2":                            "Apache-2.0",
		"APLv2":                           "Apache-2.0",

		// MIT variants
		"MIT":             "MIT",
		"mit":             "MIT",
		"Mit":             "MIT",
		"MiT":             "MIT",
		"MIT ":            "MIT",
		"MIT License":     "MIT",
		"MIT Licence":     "MIT",
		"MIT licence":     "MIT",
		"MIT license":     "MIT",
		"MIT Lisence":     "MIT",
		"MIT LICENSE":     "MIT",
		"MIT License.":    "MIT",
		"MIT-LICENSE":     "MIT",
		"MIT-License":     "MIT",
		"MIT-Style":       "MIT",
		"MIT-like":        "MIT",
		"MIT/X":           "MIT",
		"MIT/X11":         "MIT",
		"M.I.T":           "MIT",
		"M.I.T.":          "MIT",
		"MTI":             "MIT",
		"LICENSE-MIT":     "MIT",
		"MIT_License":     "MIT",
		"MIT +no-false-attribs": "MITNFA",

		// GPL variants
		"GPL":        "GPL-3.0-or-later",
		"Gpl":        "GPL-3.0-or-later",
		"GLP":        "GPL-3.0-or-later",
		"GNU":        "GPL-3.0-or-later",
		"GUN":        "GPL-3.0-or-later",
		"GNU-GPL":    "GPL-3.0-or-later",
		"GNU/GPL":    "GPL-3.0-or-later",
		"GPL 2":      "GPL-2.0-only",
		"GPL 2.0":    "GPL-2.0-only",
		"GPL V2":     "GPL-2.0-only",
		"GPL v2":     "GPL-2.0-only",
		"GPL v.2":    "GPL-2.0-only",
		"GPL2":       "GPL-2.0-only",
		"GPL-2":      "GPL-2.0-only",
		"GPLV2":      "GPL-2.0-only",
		"GPLv2":      "GPL-2.0-only",
		"Gpl-2.0":    "GPL-2.0-only",
		"Gpl2":       "GPL-2.0-only",
		"GPL 3":      "GPL-3.0-or-later",
		"GPL 3.0":    "GPL-3.0-or-later",
		"GPL V3":     "GPL-3.0-or-later",
		"GPL V3.0":   "GPL-3.0-or-later",
		"GPL v3":     "GPL-3.0-or-later",
		"GPL v3.0":   "GPL-3.0-or-later",
		"GPL-3":      "GPL-3.0-or-later",
		"GPL3":       "GPL-3.0-or-later",
		"GPL3.0":     "GPL-3.0-or-later",
		"GPLV3":      "GPL-3.0-or-later",
		"GPLv3":      "GPL-3.0-or-later",
		"Gpl-3.0":    "GPL-3.0-or-later",
		"GLPv3":      "GPL-3.0-or-later",
		"Gpl v3":     "GPL-3.0-or-later",
		"GPL-1":      "GPL-1.0-only",
		"GPL Version 3":          "GPL-3.0-or-later",
		"GPL-2.0-":                "GPL-2.0-only",
		"GPL-2.0+":                "GPL-2.0-or-later",
		"GPL2+":                   "GPL-2.0-or-later",
		"GPLv2+":                  "GPL-2.0-or-later",
		"GPL-1.0+":                "GPL-1.0-or-later",
		"GPL v3+":                 "GPL-3.0-or-later",
		"GPL3.0+":                 "GPL-3.0-or-later",
		"GPLv3+":                  "GPL-3.0-or-later",
		"GNU GPL":                 "GPL-3.0-or-later",
		"GNU GPL 3":               "GPL-3.0-or-later",
		"GNU GPL 3.0":             "GPL-3.0-or-later",
		"GNU GPL V2":              "GPL-2.0-only",
		"GNU GPL V3.0":            "GPL-3.0-or-later",
		"GNU GPL v2":              "GPL-2.0-only",
		"GNU GPL v2.0":            "GPL-2.0-only",
		"GNU GPL v3":              "GPL-3.0-or-later",
		"GNU GPL v3.0":            "GPL-3.0-or-later",
		"GNU GPL ver 3":           "GPL-3.0-or-later",
		"GNU GPLv2":               "GPL-2.0-only",
		"GNU GPLv3":               "GPL-3.0-or-later",
		"GNU GPLv3+":              "GPL-3.0-or-later",
		"GNU GLP v3.0":            "GPL-3.0-or-later",
		"GNU GENERAL PUBLIC LICENSE":         "GPL-3.0-or-later",
		"GNU GENERAL PUBLIC LICENSE Version 2": "GPL-2.0-only",
		"GNU General Public License":         "GPL-3.0-or-later",
		"GNU General Public License v2.0":    "GPL-2.0-only",
		"GNU General Public License v3":      "GPL-3.0-or-later",
		"GNU General Public License, version 2": "GPL-2.0-only",
		"GNU General Public":                 "GPL-3.0-or-later",
		"GNU License v3":                     "GPL-3.0-or-later",
		"GNU V3":                             "GPL-3.0-or-later",
		"GNU v2":                             "GPL-2.0-only",
		"GNU/GPLv2":                          "GPL-2.0-only",
		"Gnu public license v2.0":            "GPL-2.0-only",
		"license GPLv2":                      "GPL-2.0-only",

		// LGPL variants
		"LGPL":           "LGPL-3.0-or-later",
		"LGPL 2.1":       "LGPL-2.1-only",
		"LGPL 3":         "LGPL-3.0-or-later",
		"LGPL 3.0":       "LGPL-3.0-or-later",
		"LGPL v2":        "LGPL-2.0-only",
		"LGPL v3":        "LGPL-3.0-or-later",
		"LGPL-2":         "LGPL-2.0-only",
		"LGPL-3":         "LGPL-3.0-or-later",
		"LGPL2":          "LGPL-2.0-only",
		"LGPL2.1":        "LGPL-2.1-only",
		"LGPL3":          "LGPL-3.0-or-later",
		"LGPL3.0":        "LGPL-3.0-or-later",
		"LGPLv2.1":       "LGPL-2.1-only",
		"LGPLv3":         "LGPL-3.0-or-later",
		"LGLP3":          "LGPL-3.0-or-later",
		"LGPL.v3":        "LGPL-3.0-or-later",
		"LGPL:":          "LGPL-3.0-or-later",
		"LGPL Version 3.0":        "LGPL-3.0-or-later",
		"LGPL v2+":                 "LGPL-2.0-or-later",
		"LGPL2.1+":                 "LGPL-2.1-or-later",
		"LGPL3+":                   "LGPL-3.0-or-later",
		"LGPLv3+":                  "LGPL-3.0-or-later",
		"LGPL-2.0+":                "LGPL-2.0-or-later",
		"LGPL-2.1+":                "LGPL-2.1-or-later",
		"LGPL-3.0+":                "LGPL-3.0-or-later",
		"GNU LGPL v3.0":            "LGPL-3.0-or-later",
		"GNU Lesser General Public License v2":   "LGPL-2.0-only",
		"GNU Lesser General Public License v2.0": "LGPL-2.0-only",
		"GNU Lesser General Public License v2.1": "LGPL-2.1-only",
		"GNU Lesser General Public License v3":   "LGPL-3.0-or-later",
		"GNU Lesser General Public License v3.0": "LGPL-3.0-or-later",
		// Note: spdx-correct.js maps these to LGPL-2.1-only
		"GNU LESSER GENERAL PUBLIC LICENSE":  "LGPL-2.1-only",
		"LESSER GENERAL PUBLIC LICENSE":      "LGPL-2.1-only",

		// AGPL variants
		"AGPL":         "AGPL-3.0-or-later",
		"AGPL 3":       "AGPL-3.0-or-later",
		"AGPL 3.0":     "AGPL-3.0-or-later",
		"AGPL v3":      "AGPL-3.0-or-later",
		"AGPL-3":       "AGPL-3.0-or-later",
		"AGPL3":        "AGPL-3.0-or-later",
		"AGPLV3":       "AGPL-3.0-or-later",
		"AGPLv3":       "AGPL-3.0-or-later",
		"AGPLv3+":      "AGPL-3.0-or-later",
		"APGLv3":       "AGPL-3.0-or-later",
		"AGPL-1.0":     "AGPL-1.0-only",
		"AGPL-1.0+":    "AGPL-1.0-or-later",
		"AGPL-3.0+":    "AGPL-3.0-or-later",
		"Affero GPL":               "AGPL-3.0-or-later",
		"Affero GPL v3":            "AGPL-3.0-or-later",
		"Affero GPL3":              "AGPL-3.0-or-later",
		"Affero-GPL":               "AGPL-3.0-or-later",
		"Affero General Public License v3": "AGPL-3.0-or-later",
		"GNU Affero GPL 3.0":       "AGPL-3.0-or-later",
		"GNU Affero GPLv3":         "AGPL-3.0-or-later",
		"GNU AFFERO GENERAL PUBLIC LICENSE": "AGPL-3.0-or-later",
		"AFFERO GENERAL PUBLIC LICENSE":     "AGPL-3.0-or-later",
		"GNU AGPL v3.0":            "AGPL-3.0-or-later",

		// MPL variants
		"MPL":                          "MPL-2.0",
		"MPL 2":                        "MPL-2.0",
		"MPL 2.0":                      "MPL-2.0",
		"MPL V2":                       "MPL-2.0",
		"MPL v2":                       "MPL-2.0",
		"MPL v2.0":                     "MPL-2.0",
		"MPL-2":                        "MPL-2.0",
		"MPL/2.0":                      "MPL-2.0",
		"MPL2":                         "MPL-2.0",
		"MPL2.0":                       "MPL-2.0",
		"MPLV2":                        "MPL-2.0",
		"MPLv2":                        "MPL-2.0",
		"MPLv2.0":                      "MPL-2.0",
		"Mozilla Public License":      "MPL-2.0",
		"Mozilla Public License 1.1":  "MPL-1.1",
		"Mozilla Public License 2.0":  "MPL-2.0",
		"Mozilla Public License version 2":    "MPL-2.0",
		"Mozilla Public License, v. 2.0":      "MPL-2.0",
		"Mozilla Public License, version 2.0": "MPL-2.0",

		// Unlicense variants
		"Unlicense":                   "Unlicense",
		"UNLICENSE":                   "Unlicense",
		"Unlicence":                   "Unlicense",
		"Unlicensed":                  "Unlicense",
		"UNLICENSED":                  "Unlicense",
		"UNLICNSE":                    "Unlicense",
		"The Unlicense":               "Unlicense",
		"Public Domain (UNLISCENSE)":  "Unlicense",
		"Public Domain (Unlicense)":   "Unlicense",
		"Public Domain <Unlicense>":   "Unlicense",
		"Public domain(unlicense)":    "Unlicense",
		"Public-domain (Unlicense)":   "Unlicense",

		// WTFPL variants
		"WTFPL":                  "WTFPL",
		"Wtfpl":                  "WTFPL",
		"WTF":                    "WTFPL",
		"WTFGPL":                 "WTFPL",
		"WTFPL 2":                "WTFPL",
		"WTFPLv2":                "WTFPL",
		"WTHPL v1.0.0":           "WTFPL",
		"DWTFYW":                 "WTFPL",
		"DWTFYW License":         "WTFPL",
		"DWTFYWPL":               "WTFPL",
		"Do what the fuck you want to public license": "WTFPL",

		// CC variants
		"CC0":                    "CC0-1.0",
		"CC BY 3.0":              "CC-BY-3.0",
		"CC BY 4.0":              "CC-BY-4.0",
		"CC-BY 3.0":              "CC-BY-3.0",
		"CC-BY 4.0 International": "CC-BY-4.0",
		"Cc-by-3.0":              "CC-BY-3.0",
		"Attribution-NonCommercial": "CC-BY-NC-4.0",

		// Other licenses
		"ISC":        "ISC",
		"Isc":        "ISC",
		"ISD":        "ISC",
		"IST":        "ISC",
		"Artistic":            "Artistic-2.0",
		"Artistic 2.0":        "Artistic-2.0",
		"Artistic License":    "Artistic-2.0",
		"Artistic License 2.0": "Artistic-2.0",
		"Beerware":            "Beerware",
		"BeerWare":            "Beerware",
		"Beer-Ware":           "Beerware",
		"BEER":                "Beerware",
		"BEERWARE":            "Beerware",
		"Boost":               "BSL-1.0",
		"BOOST":               "BSL-1.0",
		"CDDL":                "CDDL-1.1",
		"Eclipse":             "EPL-1.0",
		"Eclipse Public License":          "EPL-1.0",
		"Eclipse Public License 1.0":      "EPL-1.0",
		"Eclipse Public License (EPL)":    "EPL-1.0",
		"Universal Permissive License":    "UPL-1.0",
		"UPL":                 "UPL-1.0",
		"Zlib":                "Zlib",
		"ZLIB":                "Zlib",
		"Zlib/libpng":         "Zlib",
	}

	for input, expected := range cases {
		t.Run(input, func(t *testing.T) {
			result, err := Normalize(input)
			if err != nil {
				t.Errorf("Normalize(%q) failed: %v", input, err)
				return
			}
			if result != expected {
				t.Errorf("Normalize(%q) = %q, want %q", input, result, expected)
			}
		})
	}
}
